image:
  file: .gitpod.Dockerfile

# tasks:
  # - init: yarn install && yarn run build
  #   command: yarn run start
# tasks:
# - before: npm install -g expo-cli
#   init: npm install
  # command: expo start --host tunnel
